<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="AsusVivobook15" failures="1" tests="1" name="Test" time="14.252" errors="0" timestamp="2025-09-01T17:22:32 IST">
  <testcase classname="pckgaeO.Login0" name="Login_001" time="8.361">
    <failure type="java.lang.AssertionError" message="testcase failed expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index]">
      <![CDATA[java.lang.AssertionError: testcase failed expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login] but found [https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index]
at pckgaeO.Login0.Login_001(Login0.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Login_001 -->
  <testcase classname="pckgaeO.Login0" name="Login_004" time="0.0">
    <ignored/>
  </testcase> <!-- Login_004 -->
  <testcase classname="pckgaeO.Login0" name="Login_002" time="0.0">
    <ignored/>
  </testcase> <!-- Login_002 -->
  <testcase classname="pckgaeO.Login0" name="Login_003" time="0.0">
    <ignored/>
  </testcase> <!-- Login_003 -->
</testsuite> <!-- Test -->
